<a href="https://colab.research.google.com/github/srikanth15650/test/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

In [5]:
temperatures  = np.array([ 1, 2, 3, 4, 5,
                          6, 7, 8, 9, 10,
                           11, 12, 13, 14, 15,
                           16, 17, 18, 19, 20,
                           21, 22, 23, 24, 25,
                           26, 27, 28, 29, 30])

In [6]:
print(temperatures)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


In [7]:
print(f"Shape: {temperatures.shape}")
print(f"Shape: {temperatures.size}")
print(f"Shape: {temperatures.dtype}")

Shape: (30,)
Shape: 30
Shape: int64


In [10]:
temperatures_reshaped = temperatures.reshape(5,6)

In [25]:
print(f"Shape: {temperatures_reshaped.shape}")
print(f"Shape: {temperatures_reshaped.size}")
print(f"Shape: {temperatures_reshaped.dtype}")
print(temperatures_reshaped)

Shape: (5, 6)
Shape: 30
Shape: int64
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]


In [24]:
first_week_temperatures = temperatures_reshaped[0]
print(first_week_temperatures)

[1 2 3 4 5 6]


In [19]:
second_week_temperatures = temperatures_reshaped[1]
print(second_week_temperatures)

[ 7  8  9 10 11 12]


In [20]:
second_week_fourth_day_temperatures = temperatures_reshaped[1,3]
print(f"second_week_temperatures {second_week_fourth_day_temperatures}")


second_week_temperatures 10


In [51]:
tue_temps = temperatures_reshaped[0:4, 1]

print(tue_temps)

[ 2  8 14 20]


Broadcasting


In [26]:
temp_fahrenheit = temperatures_reshaped * 9 / 5 + 32

In [27]:
print(temp_fahrenheit)

[[33.8 35.6 37.4 39.2 41.  42.8]
 [44.6 46.4 48.2 50.  51.8 53.6]
 [55.4 57.2 59.  60.8 62.6 64.4]
 [66.2 68.  69.8 71.6 73.4 75.2]
 [77.  78.8 80.6 82.4 84.2 86. ]]


In [30]:
cooler_days = temperatures [ temperatures <= 25]

In [31]:
print(cooler_days)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [32]:
matrix = np.array([[34, 2, 2],[1, 4, 5],[25, 2, 5],[55, 2 ,1]])
print(matrix)

[[34  2  2]
 [ 1  4  5]
 [25  2  5]
 [55  2  1]]


In [33]:
matrix + 10

array([[44, 12, 12],
       [11, 14, 15],
       [35, 12, 15],
       [65, 12, 11]])

In [34]:
m2 = np.array([1 ,10, 100])
matrix + m2

array([[ 35,  12, 102],
       [  2,  14, 105],
       [ 26,  12, 105],
       [ 56,  12, 101]])

In [35]:
matrix * m2

array([[ 34,  20, 200],
       [  1,  40, 500],
       [ 25,  20, 500],
       [ 55,  20, 100]])

In [36]:
m3 = ([2],
      [4],
      [5],
      [6])

In [37]:
matrix / m3

array([[17.        ,  1.        ,  1.        ],
       [ 0.25      ,  1.        ,  1.25      ],
       [ 5.        ,  0.4       ,  1.        ],
       [ 9.16666667,  0.33333333,  0.16666667]])

In [41]:
m4 = np.array([[3, 4, 5],
              [4, 5, 6],
              [9, 8, 9],
              [32, 4, 5]])

In [42]:
matrix + m4

array([[37,  6,  7],
       [ 5,  9, 11],
       [34, 10, 14],
       [87,  6,  6]])